### ISSUE TITLE
Unable to toggle the monitors status while Android “Enhanced Version” Client set the video resolution to “Native” or “Native Full-Screen”

### ISSUE THREAD

**Issue by GeekerCloud-official** [qiin2333/sunshine-control-panel#1]
As I set the Display preparation to 
![image](https://github.com/user-attachments/assets/909c599a-c0ef-49b4-bc21-d792c42d6674)
but it dosent toggle off my monitors and set the VD to main display

![image](https://github.com/user-attachments/assets/51deeec3-f74c-4f3b-aafc-7734ed31780e)
![image](https://github.com/user-attachments/assets/ab52dcbc-b585-4da7-952a-b63e1984b4eb)
![image](https://github.com/user-attachments/assets/ce82ada4-59d5-437a-b890-122800e136ef)
As the figures above,the VD did not be sat as the main display and both my two monitors did not be toggled off

**Comment by qiin2333** [comment]
Make sure your VD has client required resolution or refresh rate, And turn on options of "Game optimize".

**Comment by GeekerCloud-official** [comment]
> Make sure your VD has client required resolution or refresh rate, And turn on option of "Game optimize". Otherwise the frame capturer will fallback to your main active display.
Great! Problem sloved. I found some “Display  Spoofers” I bought before and pluged into my card and it seems working more smooth and stablely! but I met a new problems that I try to enable the "Performace Overlay" in Android “Enhanced Version” Client and the app directly crashed. **I try to reinstall the app and it worked.**
![image](https://github.com/user-attachments/assets/f4fac775-0533-4e44-a3d8-e1261510a8d1)
